#!/bin/bash

# this script generates list of random passwords 

# A random number as a password 
PASSWORD="${RANDOM}"
echo "${PASSWORD}"

# Three random numbers together 
PASSWORD="${RANDOM}${RANDOM}${RANDOM}"
echo "${PASSWORD}"

# Use the current date and time as the basis for the password
PASSWORD=$(date +%s) 
echo "${PASSWORD}"

# Use nanoseconds to act as randomization
PASSWORD=$(date +%s%N)
echo "${PASSWORD}"

# A better password 
PASSWORD=$(date +%s%N | sha256sum | head -c8)
echo "${PASSWORD}"

#An even better password
PASSWORD=$(date +%s%N | sha256sum | head -c8)
echo "${PASSWORD}"

# password with  special charcters 
SPECIAL_CHARACTER=$(echo '@!#%^^$*()+' |fold -w1 | shuf | head -c1) # visit man to know about shuf and fold
echo "${SPECIAL_CHARACTER}${PASSWORD}${SPECIAL_CHARACTER}"
