#!/bin/bash

# display the top three most visited url for a given web server log file

LOG_FILE="${1}"

if [ ! -e ${LOG_FILE} ]
then
   echo "can not open ${LOG_FILE} file" >&2
   exit 1
fi

cut -d '"' -f 2 ${LOG_FILE} | cut -d ' ' -f 2 | sort | uniq -c | sort -n | tail -3       
